import { serve } from "https://deno.land/std@0.190.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2.39.3";
import {
import { getCorsHeaders, handleCorsOptions } from "../_shared/cors.ts";
  GEMINI_API_BASE,
  getGeminiApiKey,
  convertContentToGeminiParts,
} from "../_shared/geminiClient.ts";


serve(async (req) => {
  const optionsResponse = handleCorsOptions(req);
  if (optionsResponse) return optionsResponse;
  const corsHeaders = getCorsHeaders(req);
  }

  try {
    const authHeader = req.headers.get("Authorization");
    if (!authHeader) {
      throw new Error("Unauthorized");
    }

    const supabase = createClient(
      Deno.env.get("SUPABASE_URL") ?? "",
      Deno.env.get("SUPABASE_ANON_KEY") ?? "",
      {
        global: {
          headers: { Authorization: authHeader },
        },
      }
    );

    const { imageUrl, textInstruction, userId } = await req.json();

    if (!imageUrl || !textInstruction || !userId) {
      throw new Error("Missing required fields: imageUrl, textInstruction, userId");
    }

    console.log("Adding text to image:", {
      hasImageUrl: !!imageUrl,
      instruction: textInstruction.substring(0, 50),
      userId
    });

    const ensureDataUrl = async (url: string) => {
      if (url.startsWith("data:")) return url;
      const fetched = await fetch(url);
      if (!fetched.ok) {
        throw new Error(`Failed to download reference image (${fetched.status})`);
      }
      const contentType = fetched.headers.get("Content-Type") || "image/png";
      const buffer = await fetched.arrayBuffer();
      const base64 = btoa(String.fromCharCode(...new Uint8Array(buffer)));
      return `data:${contentType};base64,${base64}`;
    };

    const referenceImageDataUrl = await ensureDataUrl(imageUrl);

    console.log("Calling Gemini for image editing...");
    
    const GEMINI_API_KEY = getGeminiApiKey();
    const aiResponse = await fetch(`${GEMINI_API_BASE}/models/gemini-2.5-flash-image-preview:generateContent?key=${GEMINI_API_KEY}`, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        contents: [
          {
            role: "user",
            parts: convertContentToGeminiParts([
              { type: "text", text: textInstruction },
              { type: "image_url", image_url: { url: referenceImageDataUrl } },
            ]),
          },
        ],
        generationConfig: {
          responseMimeType: "image/png",
        },
      }),
    });

    if (!aiResponse.ok) {
      const errorText = await aiResponse.text();
      console.error("Nano Banana API error:", {
        status: aiResponse.status,
        statusText: aiResponse.statusText,
        errorText: errorText.substring(0, 500)
      });
      
      // Try to parse error as JSON for more details
      let errorDetails = errorText;
      try {
        const errorJson = JSON.parse(errorText);
        console.error("Nano Banana API error details:", errorJson);
        errorDetails = JSON.stringify(errorJson);
      } catch {
        // Not JSON, use raw text
      }
      
      // Handle specific error cases
      if (aiResponse.status === 429) {
        throw new Error("Rate limit exceeded. Please wait a moment and try again.");
      }
      if (aiResponse.status === 402) {
        throw new Error("AI credits depleted. Please add credits to your workspace in Settings.");
      }
      if (aiResponse.status === 401) {
        throw new Error("API key invalid or expired. Please contact support.");
      }
      if (aiResponse.status === 400) {
        throw new Error(`Invalid request to AI API: ${errorDetails.substring(0, 200)}`);
      }
      
      throw new Error(`AI generation failed (${aiResponse.status}): ${errorDetails.substring(0, 200)}`);
    }

    const aiData = await aiResponse.json();
    console.log("Gemini image edit response received");

    const parts = aiData?.candidates?.[0]?.content?.parts || [];
    const imagePart = parts.find((part: any) => part?.inlineData);
    const generatedImageUrl = imagePart?.inlineData
      ? `data:${imagePart.inlineData.mimeType || "image/png"};base64,${imagePart.inlineData.data}`
      : undefined;
    
    if (!generatedImageUrl) {
      console.error("No image in AI response:", JSON.stringify(aiData, null, 2));
      throw new Error("No image generated by AI");
    }

    console.log("Image with text generated successfully");

    return new Response(
      JSON.stringify({ 
        imageUrl: generatedImageUrl,
        success: true 
      }),
      {
        headers: { ...corsHeaders, "Content-Type": "application/json" },
        status: 200,
      }
    );
  } catch (error: any) {
    console.error("[add-text-to-image] Error:", error);
    const errorMessage = error instanceof Error ? error.message : 'Unknown error occurred';
    return new Response(
      JSON.stringify({ error: errorMessage }),
      {
        status: error instanceof Error && errorMessage.includes('Rate limit') ? 429 :
                error instanceof Error && errorMessage.includes('credits') ? 402 : 400,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      }
    );
  }
});
