// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;
const LOCAL_FUNCTIONS_URL = import.meta.env.VITE_SUPABASE_FUNCTIONS_URL?.replace(/\/$/, "");

// Validate environment variables to prevent crashes
if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  console.error('❌ Missing Supabase environment variables!');
  console.error('SUPABASE_URL:', SUPABASE_URL ? '✓ Set' : '✗ Missing');
  console.error('SUPABASE_PUBLISHABLE_KEY:', SUPABASE_PUBLISHABLE_KEY ? '✓ Set' : '✗ Missing');
  console.error('Please check your .env file and ensure VITE_SUPABASE_URL and VITE_SUPABASE_PUBLISHABLE_KEY are set.');
  
  // Show user-friendly error in browser
  if (typeof window !== 'undefined') {
    document.body.innerHTML = `
      <div style="padding: 40px; font-family: system-ui; max-width: 600px; margin: 50px auto;">
        <h1 style="color: #dc2626; margin-bottom: 20px;">Configuration Error</h1>
        <p style="color: #374151; margin-bottom: 10px;">Missing required environment variables:</p>
        <ul style="color: #6b7280; margin-left: 20px;">
          <li>${!SUPABASE_URL ? 'VITE_SUPABASE_URL' : ''}</li>
          <li>${!SUPABASE_PUBLISHABLE_KEY ? 'VITE_SUPABASE_PUBLISHABLE_KEY' : ''}</li>
        </ul>
        <p style="color: #6b7280; margin-top: 20px;">Please check your <code>.env</code> file in the <code>asala-studio</code> directory and restart the dev server.</p>
      </div>
    `;
  }
  
  // Still throw to prevent further execution
  throw new Error('Missing Supabase environment variables. Check console for details.');
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

const fetchWithLocalFunctionOverride: typeof fetch = async (input, init) => {
  if (!LOCAL_FUNCTIONS_URL) {
    return fetch(input, init);
  }

  const originalUrl =
    typeof input === "string"
      ? input
      : input instanceof URL
        ? input.toString()
        : input.url;

  if (!originalUrl.includes("/functions/v1/generate-madison-image")) {
    return fetch(input, init);
  }

  const rewrittenUrl = originalUrl.replace(
    `${SUPABASE_URL.replace(/\/$/, "")}/functions/v1`,
    LOCAL_FUNCTIONS_URL,
  );

  console.info("[Supabase] Routing generate-madison-image to local Edge Function", {
    from: originalUrl,
    to: rewrittenUrl,
  });

  if (input instanceof Request) {
    return fetch(new Request(rewrittenUrl, input), init);
  }

  return fetch(rewrittenUrl, init);
};

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  global: {
    fetch: fetchWithLocalFunctionOverride,
  },
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
